### ISSUE TITLE
Dataset zip file TrecClassification.zip

### ISSUE THREAD

**Issue by sayef** [kristinamb15/question-classification#1]
Hi Kristina,

Thank you so much for this awesome repository. I was wondering if you would like to share the dataset zip file that you prepared from the original dataset. I am planning to work on the same dataset. As you have already worked on this, it would save a lot of time for students like us. 

Regards,
Sayef

**Comment by kristinamb15** [comment]
Oops - totally forgot I hadn't uploaded it, because it was a large file. It should be there now!

**Comment by sayef** [comment]
@kristinamb15 Thanks a lot. :)
